{{- if .Values.externalSecrets.enabled }}
{{- $secretStoreRefKind := .Values.externalSecrets.secretStoreRef.kind -}}
{{- $secretStoreRefName := .Values.externalSecrets.secretStoreRef.name -}}
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-es"
  namespace: {{ .namespace | default "kyverno" }}
spec:
  secretStoreRef:
    kind: {{ $secretStoreRefKind | default "ClusterSecretStore" }}
    name: {{ $secretStoreRefName | default "gcp-store" }}
  target:
    name: {{ .name }}
    {{- if eq .name "regsecret" }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{`"{{ .regsecret | toString }}"`}}
    creationPolicy: "Orphan"
    {{- else }}
    creationPolicy: "Owner"
    {{- end }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
